import { Geist, Geist_Mono } from "next/font/google";
import { AdminSidebar } from "./components/sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen overflow-hidden">
          {/* Fixed Left Sidebar */}
          <div className="w-1/3 h-screen fixed top-0 left-0 overflow-y-auto">
            <AdminSidebar />
          </div>

          {/* Scrollable Right Content */}
          <main className="ml-[33.33%] w-2/3 h-screen overflow-y-auto bg-[#F5F5F5] p-4">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
